FROM registry.access.redhat.com/ubi9/python-311

WORKDIR /app

COPY counter.py /app/
# RUN python3 -m pip install --no-cache-dir --upgrade -r requirements.txt
user 0
RUN chmod g+w /app/
user default

EXPOSE 8080

CMD ["python3", "counter.py"]
