apiVersion: v1
imagePullSecrets:
- name: hostmount-anyuid-dockercfg-cvzk5
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-08-23T15:47:50Z"
  name: hostmount-anyuid
  namespace: demo
  resourceVersion: "9793806"
  uid: 8856177c-03e5-43d1-9d6b-d706107d888b
secrets:
- name: hostmount-anyuid-dockercfg-cvzk5
