apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- daemonset.yaml
# oc create sa hostmount-anyuid
- hostmount-anyuid.yaml
# oc adm policy add-scc-to-user hostmount-anyuid -n demo -z  hostmount-anyuid
- rolebinding.yaml
